image: fedora:27

stages:
  - test

before_script:
  - dnf install -y gcc meson gettext itstool redhat-rpm-config git
                   gtk3-devel gnome-autoar-devel gnome-desktop3-devel
                   gobject-introspection-devel libselinux-devel
                   libxml2-devel tracker-devel desktop-file-utils
                   libgexiv2-devel gcovr

test:
  stage: test
  script:
    - meson _build . -Db_coverage=true -Ddisplay-tests=false
    - ninja test -C _build
    - gcovr --root=.
      --exclude=_build/src/
      --exclude=_build/../data/
      --exclude=_build/../eel/check-program.c
      --exclude=_build/../eel/eel-debug.c
      --exclude=_build/../eel/eel-lib-self-check-functions.c
      --exclude=_build/../eel/eel-self-checks.c
      --exclude=_build/../src/animation/
      --exclude=_build/../src/gtk/
      --exclude=_build/../src/nautilus-lib-self-check-functions.c
      --exclude=_build/../src/nautilus-self-check-functions.c
      --exclude=_build/../subprojects/libgd/
      --exclude=_build/../test/
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
