variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
- test
- cross_distro

.test_template: &distro_test
  script:
    - meson _build .
    - cd _build
    - ninja test

flatpak:master:
    image: registry.gitlab.com/alatiera/gnome-nightly-oci/gnome-master:latest
    stage: test
    script:
    - flatpak-builder --stop-at=nautilus app build-aux/flatpak/org.gnome.Nautilus.json
    # Make sure to keep this in sync with the Flatpak manifest, all arguments
    # are passed except the config-args because we build it ourselves
    - flatpak-builder --run app build-aux/flatpak/org.gnome.Nautilus.json meson --prefix=/app --libdir=/app/lib -Dprofile=development _build
    - flatpak-builder --run app build-aux/flatpak/org.gnome.Nautilus.json ninja -C _build install
    - flatpak-builder --finish-only --repo=repo app build-aux/flatpak/org.gnome.Nautilus.json
    # Make a Flatpak Nautilus bundle for people to test
    - flatpak build-bundle repo nautilus-dev.flatpak --runtime-repo=https://sdk.gnome.org/gnome-nightly.flatpakrepo org.gnome.NautilusDevel
    # Run automatic tests inside the Flatpak env
    - flatpak-builder --run app build-aux/flatpak/org.gnome.Nautilus.json ninja -C _build test
    artifacts:
        paths:
        - nautilus-dev.flatpak
        - _build/meson-logs/meson-log.txt
        - _build/meson-logs/testlog.txt
        expire_in: 2 days
    cache:
        paths:
        - .flatpak-builder/cache

# Pick any distro to build the coverage
fedora:rawhide:
    image: registry.gitlab.com/alatiera/natutilus-oci-images/amd64/fedora:rawhide
    stage: cross_distro
    script:
    - meson _build . -Db_coverage=true
    # Coverage data contains paths relative to the build directory,
    # so changing to it makes writing filter expressions easier.
    #
    # _build/src/ contains generated sources, so that is filtered out as well.
    - cd _build
    - ninja test
    - gcovr --root=.
        --exclude=src/
        --exclude=../data/
        --exclude=../eel/check-program.c
        --exclude=../eel/eel-debug.c
        --exclude=../eel/eel-lib-self-check-functions.c
        --exclude=../eel/eel-self-checks.c
        --exclude=../src/animation/
        --exclude=../src/gtk/
        --exclude=../src/nautilus-lib-self-check-functions.c
        --exclude=../src/nautilus-self-check-functions.c
        --exclude=../subprojects/libgd/
        --exclude=../test/
    coverage: '/^TOTAL.*\s+(\d+\%)$/'
    only:
    - schedules
    - web
    - tags

ubuntu:devel:
    image: registry.gitlab.com/alatiera/natutilus-oci-images/amd64/ubuntu:devel
    stage: cross_distro
    before_script:
    <<: *distro_test
    only:
    - schedules
    - web
    - tags

opensuse:tumbleweed:
    image: registry.gitlab.com/alatiera/natutilus-oci-images/amd64/opensuse:tumbleweed
    stage: cross_distro
    <<: *distro_test
    only:
    - schedules
    - web
    - tags
