image: fedora:27

stages:
  - test

before_script:
  - dnf install -y gcc meson gettext itstool redhat-rpm-config git
                   gtk3-devel gnome-autoar-devel gnome-desktop3-devel
                   gobject-introspection-devel libselinux-devel
                   libxml2-devel tracker-devel desktop-file-utils
                   libgexiv2-devel gcovr

test:
  stage: test
  script:
    - meson _build . -Db_coverage=true -Ddisplay-tests=false
    - ninja test -C _build
    - gcovr --root=_build/
      --exclude=data/
      --exclude=eel/check-program.c
      --exclude=eel/eel-debug.c
      --exclude=eel/eel-lib-self-check-functions.c
      --exclude=src/animation/
      --exclude=src/gtk/
      --exclude=subprojects/libgd/
      --exclude=test/
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
