image: fedora:rawhide

stages:
  - test

before_script:
# This helps avoid errors until a F28 stable image materializes.
  - rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-29-primary
  - dnf install -y gcc meson gettext itstool redhat-rpm-config git
                   gtk3-devel gnome-autoar-devel gnome-desktop3-devel
                   gobject-introspection-devel libselinux-devel
                   libxml2-devel tracker-devel desktop-file-utils
                   libgexiv2-devel gcovr

# Coverage data contains paths relative to the build directory,
# so changing to it makes writing filter expressions easier.
#
# _build/src/ contains generated sources, so that is filtered out as well.
test:
  stage: test
  script:
    - meson _build . -Db_coverage=true -Ddisplay-tests=false
    - cd _build
    - ninja test
# git blame me and read the log. ;)
#    - gcovr --root=.
#      --exclude=src/
#      --exclude=../data/
#      --exclude=../eel/check-program.c
#      --exclude=../eel/eel-debug.c
#      --exclude=../eel/eel-lib-self-check-functions.c
#      --exclude=../eel/eel-self-checks.c
#      --exclude=../src/animation/
#      --exclude=../src/gtk/
#      --exclude=../src/nautilus-lib-self-check-functions.c
#      --exclude=../src/nautilus-self-check-functions.c
#      --exclude=../subprojects/libgd/
#      --exclude=../test/
#  coverage: '/^TOTAL.*\s+(\d+\%)$/'
