include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    GIT_SUBMODULE_STRATEGY: normal
    BUNDLE: "nautilus-dev.flatpak"

stages:
    - triage
    - test
    - cross environment
    - deploy

flatpak devel:
    extends: '.flatpak'
    stage: test
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
    variables:
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.Nautilus.yml"
        MESON_ARGS: "-Dprofile=Devel -Dtests=all"
        FLATPAK_MODULE: "nautilus"
        RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
        APP_ID: "org.gnome.NautilusDevel"

nightly:
    extends: '.publish_nightly'
    dependencies:
        - 'flatpak devel'

fedora rawhide:
    image: fedora:rawhide
    stage: cross environment
    before_script:
        - dnf update -y --nogpgcheck
        - dnf install -y 'dnf-command(builddep)' redhat-rpm-config libseccomp-devel gcovr --nogpgcheck
        - dnf builddep -y nautilus --nogpgcheck
    script:
        - meson _build .
        - cd _build
        - ninja test
    only:
        - schedules
        - web
        - tags

flatpak master:
    stage: cross environment
    dependencies: []
    variables:
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.NautilusMaster.yml"
        MESON_ARGS: "-Dprofile=Devel -Dtests=all"
        FLATPAK_MODULE: "nautilus"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.NautilusDevel"
    extends: .flatpak
    only:
        - schedules
        - web
        - tags

triage:
    image: ruby:2.4
    stage: triage
    script:
        - gem install gitlab-triage
        - gitlab-triage --token $TRIAGE_BOT_TOKEN --project-id $CI_PROJECT_PATH --host-url https://gitlab.gnome.org
    only:
        - schedules

triage:dry-run:
    image: ruby:2.4
    stage: triage
    script:
        - gem install gitlab-triage
        - gitlab-triage --dry-run --token $TRIAGE_BOT_TOKEN --project-id $CI_PROJECT_PATH --host-url https://gitlab.gnome.org
    only:
        - schedules
    when: manual

style check:
    image: registry.gitlab.gnome.org/gnome/nautilus:latest
    stage: test
    artifacts:
        name: 'Style check artifacts'
        expose_as: 'Get style check diff here'
        when: on_failure
        paths:
            - 'uncrustify.diff'
        expire_in: 14 days
    script:
        - gcc data/lineup-parameters.c `pkg-config --cflags --libs gio-2.0 gio-unix-2.0` -o data/lineup-parameters
        - LANG=C.utf8 data/run-uncrustify.sh
        - git diff --exit-code | tee uncrustify.diff
